/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as PortfolioRouteImport } from './routes/portfolio'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ProcessRouteImport } from './routes/process'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VenuesRouteImport } from './routes/venues'
import { Route as WeddingGuideRouteImport } from './routes/wedding-guide'
import { Route as WeddingGuideIndexRouteImport } from './routes/wedding-guide.index'
import { Route as WeddingGuideSlugRouteImport } from './routes/wedding-guide.$slug'
import { Route as WeddingServicesSlugRouteImport } from './routes/wedding-services.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioRoute = PortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessRoute = ProcessRouteImport.update({
  id: '/process',
  path: '/process',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VenuesRoute = VenuesRouteImport.update({
  id: '/venues',
  path: '/venues',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingGuideRoute = WeddingGuideRouteImport.update({
  id: '/wedding-guide',
  path: '/wedding-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const WeddingGuideIndexRoute = WeddingGuideIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WeddingGuideRoute,
} as any)
const WeddingGuideSlugRoute = WeddingGuideSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => WeddingGuideRoute,
} as any)
const WeddingServicesSlugRoute = WeddingServicesSlugRouteImport.update({
  id: '/wedding-services/$slug',
  path: '/wedding-services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRoute
  '/wedding-guide': typeof WeddingGuideRouteWithChildren
  '/wedding-guide/$slug': typeof WeddingGuideSlugRoute
  '/wedding-services/$slug': typeof WeddingServicesSlugRoute
  '/wedding-guide/': typeof WeddingGuideIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRoute
  '/wedding-guide/$slug': typeof WeddingGuideSlugRoute
  '/wedding-services/$slug': typeof WeddingServicesSlugRoute
  '/wedding-guide': typeof WeddingGuideIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/portfolio': typeof PortfolioRoute
  '/privacy': typeof PrivacyRoute
  '/process': typeof ProcessRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/venues': typeof VenuesRoute
  '/wedding-guide': typeof WeddingGuideRouteWithChildren
  '/wedding-guide/$slug': typeof WeddingGuideSlugRoute
  '/wedding-services/$slug': typeof WeddingServicesSlugRoute
  '/wedding-guide/': typeof WeddingGuideIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/venues'
    | '/wedding-guide'
    | '/wedding-guide/$slug'
    | '/wedding-services/$slug'
    | '/wedding-guide/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/venues'
    | '/wedding-guide/$slug'
    | '/wedding-services/$slug'
    | '/wedding-guide'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/portfolio'
    | '/privacy'
    | '/process'
    | '/services'
    | '/sitemap.xml'
    | '/venues'
    | '/wedding-guide'
    | '/wedding-guide/$slug'
    | '/wedding-services/$slug'
    | '/wedding-guide/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  PortfolioRoute: typeof PortfolioRoute
  PrivacyRoute: typeof PrivacyRoute
  ProcessRoute: typeof ProcessRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VenuesRoute: typeof VenuesRoute
  WeddingGuideRoute: typeof WeddingGuideRouteWithChildren
  WeddingServicesSlugRoute: typeof WeddingServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio': {
      id: '/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof PortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/process': {
      id: '/process'
      path: '/process'
      fullPath: '/process'
      preLoaderRoute: typeof ProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/venues': {
      id: '/venues'
      path: '/venues'
      fullPath: '/venues'
      preLoaderRoute: typeof VenuesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-guide': {
      id: '/wedding-guide'
      path: '/wedding-guide'
      fullPath: '/wedding-guide'
      preLoaderRoute: typeof WeddingGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wedding-guide/': {
      id: '/wedding-guide/'
      path: '/'
      fullPath: '/wedding-guide/'
      preLoaderRoute: typeof WeddingGuideIndexRouteImport
      parentRoute: typeof WeddingGuideRoute
    }
    '/wedding-guide/$slug': {
      id: '/wedding-guide/$slug'
      path: '/$slug'
      fullPath: '/wedding-guide/$slug'
      preLoaderRoute: typeof WeddingGuideSlugRouteImport
      parentRoute: typeof WeddingGuideRoute
    }
    '/wedding-services/$slug': {
      id: '/wedding-services/$slug'
      path: '/wedding-services/$slug'
      fullPath: '/wedding-services/$slug'
      preLoaderRoute: typeof WeddingServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WeddingGuideRouteChildren {
  WeddingGuideSlugRoute: typeof WeddingGuideSlugRoute
  WeddingGuideIndexRoute: typeof WeddingGuideIndexRoute
}

const WeddingGuideRouteChildren: WeddingGuideRouteChildren = {
  WeddingGuideSlugRoute: WeddingGuideSlugRoute,
  WeddingGuideIndexRoute: WeddingGuideIndexRoute,
}

const WeddingGuideRouteWithChildren = WeddingGuideRoute._addFileChildren(
  WeddingGuideRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  PortfolioRoute: PortfolioRoute,
  PrivacyRoute: PrivacyRoute,
  ProcessRoute: ProcessRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VenuesRoute: VenuesRoute,
  WeddingGuideRoute: WeddingGuideRouteWithChildren,
  WeddingServicesSlugRoute: WeddingServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
